#!/bin/bash

function check_depends(){
    rm -rf /tmp/deepin && mkdir -p /tmp/deepin && cd /tmp/deepin

    if ! dpkg -s python-deepin-gsettings &>/dev/null; then
        echo "python-deepin-gsettings is not installed, please install it first."
        wget "http://indicator-screenshot.qiniudn.com/python-deepin-gsettings_0.1+git20131016204258~a64de3ac19_amd64.deb"
    fi

    if ! dpkg -s python-deepin-utils &>/dev/null; then
        echo "python-deepin-utils is not installed, please install it first."
        wget "http://indicator-screenshot.qiniudn.com/python-deepin-utils_0.0.1-1+git20131213163147~b0fcaedd21_amd64.deb"
    fi

    if ! dpkg -s deepin-ui &>/dev/null; then
        echo "deepin-ui is not installed, please install it first."
        wget "http://indicator-screenshot.qiniudn.com/deepin-ui_1+git20131230221442~bfb70c7166_all.deb"
    fi

    if ! dpkg -s deepin-screenshot &>/dev/null; then
        echo "deepin-screenshot is not installed, please install it first."
        wget "http://indicator-screenshot.qiniudn.com/deepin-screenshot_2.0+git20131219150013~f58373936f_all.deb"
    fi
}

check_depends

exit 0
